version: 0.2

run-as: root

env:
  shell: 'bash'

phases:
  install:
    commands:
      - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable-x86_64-unknown-linux-gnu"
      - 'source /root/.cargo/env'

  pre_build:
    commands:
      - 'cd hello-service/lambda'
      - "rustup override set stable-x86_64-unknown-linux-gnu"

  build:
    commands:
      - "cargo build --workspace --release"

  post_build:
    commands:
      - 'cp target/release/hello hello/bootstrap'
      - 'strip hello/bootstrap'
      - 'cp target/release/another another/bootstrap'
      - 'strip another/bootstrap'


artifacts:
  files:
    - 'lambda/Cargo.toml'
  discard-paths: yes
  s3-prefix: 'lambda-artifacts'
  secondary-artifacts:
    lambda_hello:
      files:
        - 'hello-service/lambda/hello/bootstrap'
      name: 'lambda_hello'
    lambda_another:
      files:
        - 'hello-service/lambda/another/bootstrap'
      name: 'lambda_another'

cache:
  paths:
    - '/root/.cargo/registry/**/*'
    - '/root/.cargo/git/**/*'
    - 'hello-service/lambda/target/release/**/*'
