version: 0.2

run-as: root

batch:
  fast-fail: true
  build-list:
    - identifier: linux_hello
      env:
        type: LINUX_CONTAINER
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        compute-type: BUILD_GENERAL1_SMALL
        variables:
          CODE_DIR: "hello"

phases:
  install:
    commands:
      - "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable-x86_64-unknown-linux-gnu"
      - 'source /root/.cargo/env'

  pre_build:
    commands:
      - 'cd lambda/$CODE_DIR'
      - "rustup override set stable-x86_64-unknown-linux-gnu"

  build:
    commands:
      - "cargo build --release"

  post_build:
    commands:
      - "strip target/release/$CODE_DIR"
      - "mv target/release/$CODE_DIR ./bootstrap"
      - "zip -j $CODE_DIR.zip bootstrap"


artifacts:
  files:
    - 'lambda/$CODE_DIR/$CODE_DIR.zip'
  discard-paths: yes
  s3-prefix: 'lambda-artifacts'

cache:
  paths:
    - '/root/.cargo/registry/**/*'
    - '/root/.cargo/git/**/*'
    - 'lambda/$CODE_DIR/target/release/**/*'
